### ISSUE TITLE
we must have workers unlimited to run this?

### ISSUE THREAD

**Issue by zephyr-y** [TownLake/blog-samrhea-legacy#23]

**Comment by TownLake** [comment]
Workers Unlimited is probably the easiest way to subscribe, but any Cloudflare subscription that includes Workers and Workers KV will do.

**Comment by frenchvandal** [comment]
@TownLake do you use Workers KV or just Workers with your Hugo blog?

I am currently making some tests with a Hugo blog hosted on Google Firebase. I am starting from scratch, and expected traffic and storage should be so low that I could benefit from the free tier for a long long time (1 Gb storage and 10 Gb bandwith). Yet for the fun, the challenge and because I could spare $5 a month, I would be interested in trying to deploy my Hugo on Cloudflare Workers.

Just another quick question: does Cloudflare Workers imply that my custom domain to Cloudflare? Or is it two separate things?

P.S. actually a blogger is running a benchmark comparing different providers. In 2017, Firebase was the best overall. It should be out within 1 or 2 weeks and Workers will be included in the benchmark. I am very curious to see how Workers performs!

**Comment by TownLake** [comment]
I use Workers KV; that is included in the Workers Unlimited $5 plan.

This does require a hostname use Cloudflare's DNS to deploy the Workers routes.

Please do send us the link on the benchmarking!

**Comment by frenchvandal** [comment]
Thank you @TownLake! Sorry the concept of Workers is still new to me. I will give it a try 😄 

The 2020 benchmark should be published within 1-2 weeks. The 2017 benchmark is [here](https://www.savjee.be/2017/10/Static-website-hosting-who-is-fastest/), it was one of the reasons I opted for Firebase to host Hugo (besides being super easy to set up and configure).

**Comment by frenchvandal** [comment]
@TownLake here is the 2020 benchmark:
https://www.savjee.be/2020/05/benchmarking-static-website-hosting-providers/
